linters:
  enable-all: true
  disable:
    - wsl
    - bodyclose
    - tagliatelle
    - paralleltest
    - wrapcheck
    - exhaustivestruct
    - testpackage
    - varnamelen
    - nlreturn
    - gochecknoglobals
    - gofumpt
    - goimports

run:
  skip-files:
    - internal/server/router_test.go